### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Jesse-TYW-DJ** [Pr0t0ns/Discord-Token-Generator#17]
|> Proxy Error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

What can i do about it

**Comment by Jesse-TYW-DJ** [comment]
i bought iproyal ip's now but get this error now:

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/Users/me/Desktop/Code Stuff/Discord-Token-Generator-Pr0t0nGenV1.5/generator/gen.py", line 604, in run
    generate_account = create_account(proxy)
  File "/Users/me/Desktop/Code Stuff/Discord-Token-Generator-Pr0t0nGenV1.5/generator/gen.py", line 433, in create_account
    fingerprint, dcfduid, sdcfduid = get_fingerprint(proxy)
  File "/Users/me/Desktop/Code Stuff/Discord-Token-Generator-Pr0t0nGenV1.5/generator/gen.py", line 271, in get_fingerprint
    conn.request("GET", "/api/v9/experiments", payload, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

**Comment by Pr0t0ns** [comment]
make sure you have chaged the config.json file. Look for user:pass@ip:port format and set the value to "true"

**Comment by Jesse-TYW-DJ** [comment]
I did that but still got the error
