### ISSUE TITLE
cant run the program

### ISSUE THREAD

**Issue by TomerGamerTV** [Pr0t0ns/Discord-Token-Generator#6]
python3 gen.py
Traceback (most recent call last):
  File "/mnt/c/Users/tomer/Downloads/gen.py", line 5, in <module>
    from structures import ProxyPool, Proxy
  File "/home/tomer/.local/lib/python3.10/site-packages/structures.py", line 7, in <module>
    from collections import ChainMap, OrderedDict, Sequence
ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by Pr0t0ns** [comment]
You need to make sure you have pip installed all the requirement's
